const string = { type: "string" };
const strings = { type: "array", items: string };
export const AI_LISTING_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    title: string,
    description: string,
    category: string,
    category_hint: string,
    brand: string,
    item_type: string,
    color: strings,
    size: string,
    material: string,
    condition: {
      type: "string",
      enum: [
        "NEW_WITH_TAGS",
        "NEW_NO_TAGS",
        "EXCELLENT",
        "VERY_GOOD",
        "GOOD",
        "FAIR",
        "FOR_PARTS_OR_NOT_WORKING",
      ],
    },
    condition_notes: string,
    measurements: string,
    suggested_price: { type: "number" },
    seo_keywords: strings,
    key_features: strings,
    specifics: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: string,
          value: string,
          photoIndices: { type: "array", items: { type: "integer" } },
        },
        required: ["name", "value", "photoIndices"],
      },
    },
  },
  required: [
    "title",
    "description",
    "category",
    "category_hint",
    "brand",
    "item_type",
    "color",
    "size",
    "material",
    "condition",
    "condition_notes",
    "measurements",
    "suggested_price",
    "seo_keywords",
    "key_features",
    "specifics",
  ],
};
